name: Publish Build

on:
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install
        working-directory: packages/material-react-table

      - name: Build package
        run: pnpm build
        working-directory: packages/material-react-table

      - name: Publish release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pnpm pack
          gh release upload ${{ github.event.release.tag_name }} *.tgz
        working-directory: packages/material-react-table
